import os
from datetime import date, timedelta

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..dependencies import CurrentUser, get_current_user, get_db
from ..models.transaction import Transaction
from ..schemas.account import AccountCreate
from ..schemas.transaction import TransactionCreate
from ..services.accounts import create_account, list_accounts
from ..services.transactions import create_transaction

router = APIRouter()


@router.post("/seed")
async def seed_dev_data(
    db: AsyncSession = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
) -> dict[str, object]:
    environment = os.getenv("ENVIRONMENT", "development").lower()
    if environment in {"production", "prod"}:
        raise HTTPException(status_code=403, detail="Seed endpoint disabled in production")

    user_id = current_user["user_id"]
    existing_accounts = await list_accounts(db, user_id=user_id, limit=1)
    created_account = 0
    created_transactions = 0

    if existing_accounts:
        account = existing_accounts[0]
    else:
        account = await create_account(
            db,
            AccountCreate(
                provider="manual",
                external_id=None,
                name="Checking",
                type="checking",
                balance_current=2450.00,
                currency="USD",
            ),
            user_id=user_id,
        )
        created_account = 1

    for offset, (merchant, amount, category) in enumerate(
        [
            ("Whole Foods", -68.42, "groceries"),
            ("Shell", -42.77, "transport"),
            ("Payroll", 2450.00, "income"),
        ]
    ):
        external_id = f"seed-{offset}"
        existing_tx = await db.scalar(
            select(Transaction.id).where(
                Transaction.account_id == account.id,
                Transaction.external_id == external_id,
            )
        )
        if existing_tx is not None:
            continue

        await create_transaction(
            db,
            TransactionCreate(
                account_id=account.id,
                external_id=external_id,
                amount=amount,
                description=f"Seed transaction: {merchant}",
                merchant_name=merchant,
                category=category,
                date=date.today() - timedelta(days=offset),
                notes="Generated by /dev/seed",
                is_manual=True,
            ),
        )
        created_transactions += 1

    return {
        "status": "ok",
        "user_id": user_id,
        "created_account": created_account,
        "created_transactions": created_transactions,
        "account_id": account.id,
    }
